FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project directory into the container
COPY . .

# Expose the port that your Next.js app will run on
EXPOSE 3000

# Start the development server with hot reloading
CMD ["npm", "run", "dev"]