version: '3'

services:
  cache:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  database:
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_SERVER_URL=${BACKEND_URL}
  backend:
    depends_on:
      - database
      - cache
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - CORS_ORIGIN=${CORS_ORIGIN}

volumes:
  postgres-data:
  redis-data:
